# -*- coding: utf-8 -*-
"""mapk.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14TPzKKL7vW_5x1EniOsQaZQXN5-lrA8a
"""

import numpy as np

# average precision 
def apk(actual, predicted, k=7, default=0.0):
    # MAP@7, k=7
    if len(predicted)>k:
        predicted = predicted[:k]

    score = 0.0
    num_hits =0.0 

    for i, p in enumerate(predicted):
        if p in actual and p not in predicted[:i]: # 정답이 있고 중복이 아니면
            num_hits += 1.0
            score += num_hits / (i+1.0)
    
    if not actual:
        return default

    return score / min(len(actual),k)

def mapk(actual, predicted, k=7, default=0.0):
    return np.mean([apk(a,p,k,default) for a,p in zip(actual,predicted)]) # 고객별 apk 평균

